<script lang="ts">
	import { Card, CardContent, CardHeader, CardTitle } from '$lib/components/ui/card';
	import type { GameState, PlayerState } from '@gangsta/rusty';
	import { RectangleVertical } from 'lucide-svelte';
	import HeartPulse from 'lucide-svelte/icons/heart-pulse';
	import Clover from 'lucide-svelte/icons/clover';
	import { user } from '../../stores/access-token';
	import PlayingCardWithAttachments from './card/playing-card-with-attachments.svelte';
	import CCard from './card/playing-card.svelte';
	import { target } from './game';
	import ManaBubble from './mana-bubble/mana-bubble.svelte';
	import { Tooltip, TooltipContent, TooltipTrigger } from '../ui/tooltip';

	export let game: GameState;
	export let code: string;
	export let playerName: string;
	export let player: PlayerState;

	async function setPlayerTarget(player: PlayerState) {
		target.set({ Player: player.sub });
	}
</script>

<Card class="bg-transparent border-0 p-0">
	<CardHeader class="space-y-1">
		<CardTitle class="text-2xl font-bold text-center flex items-center">
			<button data-player={player.sub} on:click={() => setPlayerTarget(player)}>
				<div class="mr-4 flex items-center space-x-1">
					<div>
						{playerName}
					</div>
					<sub class="text-xs">
						{#if playerName === $user?.sub}(it's you){/if}
					</sub>
				</div>
			</button>
			<div class="flex space-x-2 items-center"></div>
			<div class="ml-auto flex flex-col">
				<div class="flex items-center">
					{#each { length: player.public_info.hand_size } as _}
						<RectangleVertical />
					{/each}
					<Tooltip>
						<TooltipTrigger>
							<div class="flex space-x-2 items-center ml-3">
								<Clover class="mr-2" />
								{player.public_info.luck_tokens}
							</div>
						</TooltipTrigger>
						<TooltipContent class="max-w-[560px] text-base p-6">
							<p class="mb-2">
								Luck Tokens are a special resource in the Vegas deck, representing the thrill of
								gambling and unpredictability. They can be used in various ways to enhance your
								gameplay, such as:
							</p>
							<ul class="list-disc mb-2 ml-6">
								<li>Activating special abilities on creatures and spells.</li>
								<li>Increasing the power of your creatures.</li>
								<li>Drawing extra cards or gaining life.</li>
								<li>Triggering unique effects like regeneration, menace, or first strike.</li>
							</ul>
							<p>
								Luck Tokens are generated by certain lands, creatures, and enchantments, making them
								a valuable part of your strategy.
							</p>
						</TooltipContent>
					</Tooltip>
					<div class="flex space-x-2 items-center ml-3">
						<HeartPulse class="mr-2" />
						{player.public_info.health}
					</div>
				</div>
				{#if Object.values(player.public_info.mana_pool).find((x) => x !== true && x > 0)}
					<div class="ml-auto flex items-center space-x-2">
						<div class="text-xs uppercase">Mana pool</div>
						{#each Object.keys(player.public_info.mana_pool) as key}
							{@const val = player.public_info.mana_pool[key]}
							{#if Number.isInteger(val)}
								{#each { length: val } as _, i}
									<ManaBubble color={key} />
								{/each}
							{/if}
						{/each}
					</div>
				{/if}
			</div>
		</CardTitle>
	</CardHeader>
	<CardContent class="space-y-4">
		<div class="flex flex-wrap gap-2">
			{#each player.public_info.cards_in_play as card, i}
				{#if typeof card.card.card_type !== 'string' && card.attached_to === null}
					<PlayingCardWithAttachments {game} cardWithDetails={card} />
				{/if}
			{/each}
		</div>
		<div class="flex flex-wrap gap-2">
			{#each player.public_info.cards_in_play as card, i}
				{#if typeof card.card.card_type === 'string' && card.attached_to === null}
					<PlayingCardWithAttachments {game} cardWithDetails={card} />
				{/if}
			{/each}
			{#each player.public_info.spells as card, i}
				<CCard {game} class="opacity-50" cardWithDetails={card}></CCard>
			{/each}
		</div>
	</CardContent>
</Card>
